### PR TITLE
Post: Create a DSC Configuration repository

### PR DESCRIPTION
**Pull request by johlju**
This change is [Reviewable](https://reviewable.io/reviews/johlju/johlju.github.io/3)

### CODE REVIEW

**Comment by johlju** [comment]
@frokensonja Can you please proof read this `2017-08-05-create-a-dsc-configuration-repository.md`

**Comment by johlju** [comment]
@frokensonja Maybe it's easier to read here;  https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md

**Comment by johlju** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 658 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMXPjzrgbQtb4aKBzT:-KrMXPjzrgbQtb4aKBzU:b-l44laq) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L658)):*
> first three lines

It's not the first three lines

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/johlju/johlju.github.io/3)*

**Comment by johlju** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 445 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMZSpHuE-N5FF32ou3:-KrMZSpHuE-N5FF32ou4:bb2l0uo) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L445)):*
> @('2012-R2-Datacenter','2016-Datacenter')

Might be `'2012-R2-Datacenter','2016-Datacenter'`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/johlju/johlju.github.io/3)*

**Comment by FrokenSonja** [comment]
Review status: 0 of 6 files reviewed at latest revision, 17 unresolved discussions.

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 35 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMWmg6MGBE0K1lHk2J:-KrMWmg6MGBE0K1lHk2K:b10sedy) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L35)):*
> And that you have all the necessary accounts on dependent
> services.

, and that you have....

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 48 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMWw087oFqDtwvHcId:-KrMWw087oFqDtwvHcIe:bbcfrp5) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L48)):*
> is 
are

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 52 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMX6hQYsTDw8uCJ8kG:-KrMX6hQYsTDw8uCJ8kH:bnelnla) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L52)):*
> flavours
forms

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 53 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMXDOSaLfQ_ej0JW0b:-KrMXDOSaLfQ_ej0JW0c:b-wv70tj) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L53)):*
> thru
through

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 89 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMXZwnhqEAo1-h3YXR:-KrMXZworIn_y80tHuUV:b-6ikebq) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L89)):*
> not 
don't

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 94 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMXgHIp3OnCwVgAYkI:-KrMXgHIp3OnCwVgAYkJ:bo5x8d9) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L94)):*
> a
an

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 145 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMY2kweUNBdiFNVgHG:-KrMY2kweUNBdiFNVgHH:b-bz8xkp) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L145)):*
> worked
is correct

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 175 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMYAPpQTnrF-U2-7P2:-KrMYAPpQTnrF-U2-7P3:b-duxtzx) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L175)):*
> not already have
donät already have

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 179 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMYLI4HEBntX-8Bv7L:-KrMYLI4HEBntX-8Bv7M:b5x4ryo) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L179)):*
> need
needs

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 256 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMZJVS3z78Wed9pyJg:-KrMZJVS3z78Wed9pyJh:b-h4l893) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L256)):*
> gonna
going to

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 383 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrM_3NAOn8Yh9ClX-pe:-KrM_3NAOn8Yh9ClX-pf:b-mi0l2k) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L383)):*
> ock 
lock icon

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 392 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrM_FdJTraehLfXFLDJ:-KrM_FdJTraehLfXFLDK:b-7jkvha) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L392)):*
> ```Markdown
> 
>    1. Repeat the previous step for the following environment variables, and make
>       sure to secure each value. Use the values you save in the previous steps.
> ```

saved

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 533 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMbwwpBA7ma9ZUSfwo:-KrMbwwpBA7ma9ZUSfwp:b8yia39) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L533)):*
> wit
with

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 557 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMc1DaSX-MtTMOWwWm:-KrMc1DaSX-MtTMOWwWn:b-bwtf8f) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L557)):*
> ```Markdown
> 
> 1. Open the file 'DscConfigurationExample.ps1' that was created above.
> 1. At the end of the file you find the following code.
> ```

you will find

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 674 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMcxOR2gi_oKqb1zxE:-KrMcxOR2gi_oKqb1zxF:brk3ltk) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L674)):*
> ue to bugs in the current version of the test framework ([DscConfiguration.Tests](https://github.com/PowerShell/DscConfiguration.Tests))
> that has not been merged yet, we need to use a branch in my fork that do have
> most fixes (known so far). My working branch is based on @PlagueHO's branch,
> which [awaiting review](https://github.com/PowerShell/DscConfiguration.Tests/pull/21)
> and I'm waiting for that to merge before being able to send in a
> pull request (PR) based on my working branch.


Find workaround for entire paragraph.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/johlju/johlju.github.io/3)*

**Comment by FrokenSonja** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/johlju/johlju.github.io/3)*

**Comment by johlju** [comment]
Review status: 5 of 6 files reviewed at latest revision, 17 unresolved discussions.

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 35 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMWmg6MGBE0K1lHk2J:-KrPltdBAGwrDvFx08qx:b-896fix) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L35)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

> And that you have all the necessary accounts on dependent
> services.

, and that you have....
</blockquote></details>

Done.

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 48 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMWw087oFqDtwvHcId:-KrPltx1C5LZZPedLuaK:b-896fix) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L48)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

> is 
are
</blockquote></details>

Done.

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 52 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMX6hQYsTDw8uCJ8kG:-KrPlxIE72t-5La7CSeJ:b-896fix) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L52)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

> flavours
forms
</blockquote></details>

Done.

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 53 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMXDOSaLfQ_ej0JW0b:-KrPlyKv-L11nEJ2NRQD:b-896fix) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L53)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

> thru
through
</blockquote></details>

Done.

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 89 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMXZwnhqEAo1-h3YXR:-KrPlz7xjy9VlYEjj4kO:b-896fix) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L89)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

> not 
don't
</blockquote></details>

Done.

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 94 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMXgHIp3OnCwVgAYkI:-KrPlzh_pYtEoFQsLyXc:b-896fix) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L94)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

> a
an
</blockquote></details>

Done.

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 145 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMY2kweUNBdiFNVgHG:-KrPm-NhrbKj3VmxqObQ:b-896fix) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L145)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

> worked
is correct
</blockquote></details>

Done.

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 175 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMYAPpQTnrF-U2-7P2:-KrPm0rxlpTXExGqL2CR:b-896fix) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L175)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

> not already have
donät already have
</blockquote></details>

Done.

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 179 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMYLI4HEBntX-8Bv7L:-KrPm1dNkKa89B7EpTJZ:b-896fix) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L179)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

> need
needs
</blockquote></details>

Done.

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 256 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMZJVS3z78Wed9pyJg:-KrPm2GwZ51p3kBfxINu:b-896fix) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L256)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

> gonna
going to
</blockquote></details>

Done.

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 383 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrM_3NAOn8Yh9ClX-pe:-KrPmFi5fR0JxEzOlQIC:b-896fix) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L383)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

> ock 
lock icon
</blockquote></details>

Done.

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 392 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrM_FdJTraehLfXFLDJ:-KrPmGZU4Wb7EW4h2423:b-896fix) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L392)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

saved
</blockquote></details>

Done.

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 445 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMZSpHuE-N5FF32ou3:-KrPmVWc7U8IxaK5XvkE:b-896fix) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L445)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> @('2012-R2-Datacenter','2016-Datacenter')

Might be `'2012-R2-Datacenter','2016-Datacenter'`

</blockquote></details>

Done.

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 533 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMbwwpBA7ma9ZUSfwo:-KrPmZyzXXiDllFU9_no:b-896fix) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L533)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

> wit
with
</blockquote></details>

Done.

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 557 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMc1DaSX-MtTMOWwWm:-KrPmcl4NS1sLin1uM2y:b-896fix) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L557)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

you will find
</blockquote></details>

Done.

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 658 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMXPjzrgbQtb4aKBzT:-KrPmy-QOCylm0dLzRTh:b-896fix) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L658)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> first three lines

It's not the first three lines
</blockquote></details>

Done.

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 674 at r1](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrMcxOR2gi_oKqb1zxE:-KrPmyiyS89tdnH5WeaY:b-896fix) ([raw file](https://github.com/johlju/johlju.github.io/blob/4ec8526c463ebb1e48dced0006dbceea9d2833a8/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L674)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

> ue to bugs in the current version of the test framework ([DscConfiguration.Tests](https://github.com/PowerShell/DscConfiguration.Tests))
> that has not been merged yet, we need to use a branch in my fork that do have
> most fixes (known so far). My working branch is based on @PlagueHO's branch,
> which [awaiting review](https://github.com/PowerShell/DscConfiguration.Tests/pull/21)
> and I'm waiting for that to merge before being able to send in a
> pull request (PR) based on my working branch.


Find workaround for entire paragraph.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/johlju/johlju.github.io/3)*

**Comment by FrokenSonja** [comment]
Review status: 5 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 652 at r2](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrPoBfv-7Ae2UfEAyfM:-KrPoBfv-7Ae2UfEAyfN:b-1f98lz) ([raw file](https://github.com/johlju/johlju.github.io/blob/281c4fe47e8478da51e21c1419f23e3a344333d1/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L652)):*
> ```Markdown
> 
> 1. Open the file appveyor.yml and add the below line directly after the *BuildID*
>    dictionary. Change to the location name to something that best fit your need.
> ```

fits your needs

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 652 at r2](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrPoNzCtRKRjmiUxVA-:-KrPoNzCtRKRjmiUxVA0:b-trd8cd) ([raw file](https://github.com/johlju/johlju.github.io/blob/281c4fe47e8478da51e21c1419f23e3a344333d1/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L652)):*
> hange to the location name to something that best fit your need.
change the location name to something that fits your needs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/johlju/johlju.github.io/3)*

**Comment by johlju** [comment]
Review status: 5 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 652 at r2](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrPoBfv-7Ae2UfEAyfM:-KrPp2mAnOLYHrh7qULy:b-896fix) ([raw file](https://github.com/johlju/johlju.github.io/blob/281c4fe47e8478da51e21c1419f23e3a344333d1/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L652)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

fits your needs
</blockquote></details>

Done.

---

*[_posts/2017-08-05-create-a-dsc-configuration-repository.md, line 652 at r2](https://reviewable.io:443/reviews/johlju/johlju.github.io/3#-KrPoNzCtRKRjmiUxVA-:-KrPp3-aTcOY7D8qOYgk:b-896fix) ([raw file](https://github.com/johlju/johlju.github.io/blob/281c4fe47e8478da51e21c1419f23e3a344333d1/_posts/2017-08-05-create-a-dsc-configuration-repository.md#L652)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

> hange to the location name to something that best fit your need.
change the location name to something that fits your needs
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/johlju/johlju.github.io/3)*

**Comment by FrokenSonja** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/johlju/johlju.github.io/3)*

**Pull request merged**
