### PR TITLE
Adding defaults for pages and adding about page

### PR DESCRIPTION
**Pull request by johlju**
This change is [Reviewable](https://reviewable.io/reviews/johlju/johlju.github.io/1)

### CODE REVIEW

**Comment by johlju** [comment]
@frokensonja can you review this one for me? In particular proof read the markdown file.

**Comment by FrokenSonja** [comment]
Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions.

---

*[_pages/about.md, line 19 at r2](https://reviewable.io:443/reviews/johlju/johlju.github.io/1#-KqrD1Dlqp_KIeB7nhYI:-KqrD1Dlqp_KIeB7nhYJ:bbnl3lt) ([raw file](https://github.com/johlju/johlju.github.io/blob/c23b57eb0d826e14667bb4fe109488d5ca3a1025/_pages/about.md#L19)):*
>  Whenever I can like to spend time

---

*[_pages/about.md, line 22 at r2](https://reviewable.io:443/reviews/johlju/johlju.github.io/1#-KqrDvWg1rs6FDiUKSWy:-KqrDvWg1rs6FDiUKSWz:bw0vrq6) ([raw file](https://github.com/johlju/johlju.github.io/blob/c23b57eb0d826e14667bb4fe109488d5ca3a1025/_pages/about.md#L22)):*
> ```Markdown
> with friends and take (shopping) weekends in different cites. A passion I have is
> to drive motocross, which I try to drive as much as I can. But driving motocross
> isn't jsyt abut the driving (and repairing), you have to focus and look ahead,
> ```

just about

---

*[_pages/about.md, line 23 at r2](https://reviewable.io:443/reviews/johlju/johlju.github.io/1#-KqrEWO0RFhI3V_vSEcY:-KqrE2tieUe3yYJ42H0H:bfv54yg) ([raw file](https://github.com/johlju/johlju.github.io/blob/c23b57eb0d826e14667bb4fe109488d5ca3a1025/_pages/about.md#L23)):*
> ```Markdown
> to drive motocross, which I try to drive as much as I can. But driving motocross
> isn't jsyt abut the driving (and repairing), you have to focus and look ahead,
> just like when coding, and most everything. You have to be steps ahead so you
> ```

and almost everything. You have to be several steps ahead so you don't get surprised by what's behind the next corner.

---

*[_pages/about.md, line 36 at r2](https://reviewable.io:443/reviews/johlju/johlju.github.io/1#-KqrEobSEvsLCcoNRqdd:-KqrEobSEvsLCcoNRqde:b-m9i2v) ([raw file](https://github.com/johlju/johlju.github.io/blob/c23b57eb0d826e14667bb4fe109488d5ca3a1025/_pages/about.md#L36)):*
> ```Markdown
> For me as a maintainer it involves mostly administrative tasks, for example
> answering issues, tagging issues, tagging pull requests, reviewing code, and
> merging code. It also involves making sure the continuous integration process
> ```

processes work

---

*[_pages/about.md, line 37 at r2](https://reviewable.io:443/reviews/johlju/johlju.github.io/1#-KqrEuV5N6YDmQC1Laqo:-KqrEuV5N6YDmQC1Laqp:b-mmdou) ([raw file](https://github.com/johlju/johlju.github.io/blob/c23b57eb0d826e14667bb4fe109488d5ca3a1025/_pages/about.md#L37)):*
> ```Markdown
> answering issues, tagging issues, tagging pull requests, reviewing code, and
> merging code. It also involves making sure the continuous integration process
> works, helping other contributors with any coding issues that arises, or they
> ```

arise, or when they get stuck.

---

*[_pages/about.md, line 42 at r2](https://reviewable.io:443/reviews/johlju/johlju.github.io/1#-KqrF5_ncFqYd4wQsLfN:-KqrF5_ncFqYd4wQsLfO:bdzlom7) ([raw file](https://github.com/johlju/johlju.github.io/blob/c23b57eb0d826e14667bb4fe109488d5ca3a1025/_pages/about.md#L42)):*
> ```Markdown
> from time to time I also get time to improve the resources myself.
> 
> My day job is at D-data AB where I belong to the unit Business Development with
> ```

Development as a Software Architect

---

*[_pages/about.md, line 44 at r2](https://reviewable.io:443/reviews/johlju/johlju.github.io/1#-KqrFFQp2DmDAJUz50Cm:-KqrFFQp2DmDAJUz50Cn:b-7t6o2n) ([raw file](https://github.com/johlju/johlju.github.io/blob/c23b57eb0d826e14667bb4fe109488d5ca3a1025/_pages/about.md#L44)):*
> ```Markdown
> My day job is at D-data AB where I belong to the unit Business Development with
> a role as Software Architect.
> My focus area are mostly integration and content management. My responsible is,
> ```

areas

---

*[_pages/about.md, line 44 at r2](https://reviewable.io:443/reviews/johlju/johlju.github.io/1#-KqrFH_vraUCxMxW-8n5:-KqrFH_vraUCxMxW-8n6:b-isxue3) ([raw file](https://github.com/johlju/johlju.github.io/blob/c23b57eb0d826e14667bb4fe109488d5ca3a1025/_pages/about.md#L44)):*
> ```Markdown
> My day job is at D-data AB where I belong to the unit Business Development with
> a role as Software Architect.
> My focus area are mostly integration and content management. My responsible is,
> ```

responsibilities are

---

*[_pages/about.md, line 45 at r2](https://reviewable.io:443/reviews/johlju/johlju.github.io/1#-KqrFOCKdp7dImh6ZyHW:-KqrFOCKdp7dImh6ZyHX:b-v3x86t) ([raw file](https://github.com/johlju/johlju.github.io/blob/c23b57eb0d826e14667bb4fe109488d5ca3a1025/_pages/about.md#L45)):*
> ```Markdown
> a role as Software Architect.
> My focus area are mostly integration and content management. My responsible is,
> among other things, the lifecycle of the software platforms. So the software
> ```

The software platforms are designed to meet the business needs in the short and long term, and that the software

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/johlju/johlju.github.io/1)*

**Comment by johlju** [comment]
Review status: 0 of 3 files reviewed at latest revision, 9 unresolved discussions.

---

*[_pages/about.md, line 19 at r2](https://reviewable.io:443/reviews/johlju/johlju.github.io/1#-KqrD1Dlqp_KIeB7nhYI:-KqrrvwxNSZqaZY_lQIy:b-k16dhl) ([raw file](https://github.com/johlju/johlju.github.io/blob/c23b57eb0d826e14667bb4fe109488d5ca3a1025/_pages/about.md#L19)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

>  Whenever I can like to spend time
</blockquote></details>

Done. Maybe. Not sure what you meant about this one?

---

*[_pages/about.md, line 22 at r2](https://reviewable.io:443/reviews/johlju/johlju.github.io/1#-KqrDvWg1rs6FDiUKSWy:-Kqrs1IP49_QG2mj_Jf4:b-896fix) ([raw file](https://github.com/johlju/johlju.github.io/blob/c23b57eb0d826e14667bb4fe109488d5ca3a1025/_pages/about.md#L22)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

just about
</blockquote></details>

Done.

---

*[_pages/about.md, line 23 at r2](https://reviewable.io:443/reviews/johlju/johlju.github.io/1#-KqrEWO0RFhI3V_vSEcY:-Kqrsbgl6f2BfcDvxNKL:b-896fix) ([raw file](https://github.com/johlju/johlju.github.io/blob/c23b57eb0d826e14667bb4fe109488d5ca3a1025/_pages/about.md#L23)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

and almost everything. You have to be several steps ahead so you don't get surprised by what's behind the next corner.
</blockquote></details>

Done.

---

*[_pages/about.md, line 36 at r2](https://reviewable.io:443/reviews/johlju/johlju.github.io/1#-KqrEobSEvsLCcoNRqdd:-KqrsfBb694W5E8ZNI5n:b-ed3v0w) ([raw file](https://github.com/johlju/johlju.github.io/blob/c23b57eb0d826e14667bb4fe109488d5ca3a1025/_pages/about.md#L36)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

processes work
</blockquote></details>

Not changed. CI is one process.  Is it correct then? :smile: 

---

*[_pages/about.md, line 37 at r2](https://reviewable.io:443/reviews/johlju/johlju.github.io/1#-KqrEuV5N6YDmQC1Laqo:-KqrsvNP5b9CS6dmEFhp:b-vr1eau) ([raw file](https://github.com/johlju/johlju.github.io/blob/c23b57eb0d826e14667bb4fe109488d5ca3a1025/_pages/about.md#L37)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

arise, or when they get stuck.
</blockquote></details>

Done. Removed last sentence.

---

*[_pages/about.md, line 42 at r2](https://reviewable.io:443/reviews/johlju/johlju.github.io/1#-KqrF5_ncFqYd4wQsLfN:-KqrszMQu77zEaOoeIZ9:b-896fix) ([raw file](https://github.com/johlju/johlju.github.io/blob/c23b57eb0d826e14667bb4fe109488d5ca3a1025/_pages/about.md#L42)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

Development as a Software Architect
</blockquote></details>

Done.

---

*[_pages/about.md, line 44 at r2](https://reviewable.io:443/reviews/johlju/johlju.github.io/1#-KqrFFQp2DmDAJUz50Cm:-Kqrt-d9vVJcB7WG3Znm:b-896fix) ([raw file](https://github.com/johlju/johlju.github.io/blob/c23b57eb0d826e14667bb4fe109488d5ca3a1025/_pages/about.md#L44)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

areas
</blockquote></details>

Done.

---

*[_pages/about.md, line 44 at r2](https://reviewable.io:443/reviews/johlju/johlju.github.io/1#-KqrFH_vraUCxMxW-8n5:-Kqrt0K_aFb12F_uIrD9:b-896fix) ([raw file](https://github.com/johlju/johlju.github.io/blob/c23b57eb0d826e14667bb4fe109488d5ca3a1025/_pages/about.md#L44)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

responsibilities are
</blockquote></details>

Done.

---

*[_pages/about.md, line 45 at r2](https://reviewable.io:443/reviews/johlju/johlju.github.io/1#-KqrFOCKdp7dImh6ZyHW:-Kqrt3w06-80vvH7Z9do:b-lncpbg) ([raw file](https://github.com/johlju/johlju.github.io/blob/c23b57eb0d826e14667bb4fe109488d5ca3a1025/_pages/about.md#L45)):*
<details><summary><i>Previously, FrokenSonja wrote…</i></summary><blockquote>

The software platforms are designed to meet the business needs in the short and long term, and that the software
</blockquote></details>

Done. Changed, but added a word at the beginning of the sentence. Okay?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/johlju/johlju.github.io/1)*

**Comment by FrokenSonja** [comment]
Reviewed 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/johlju/johlju.github.io/1)*

**Comment by johlju** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r2, 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/johlju/johlju.github.io/1#-:-Kqry8Ok3c9Htu8qbpQM:bg7igkv)*

**Pull request merged**
